name: Parking

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'server/plugins/parking/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run the databases.
        run: docker-compose up -d postgres
      - name: Build the common project.
        run: mvn -B package --file server/common/pom.xml
      - name: Install the common project.
        run: mvn -B install:install-file --file server/common/pom.xml
      - name: Build the parking plugin project.
        run: mvn -B package --file server/plugins/parking/pom.xml
